### ISSUE TITLE
Add support for gauge deltas and timestamp lag

### ISSUE THREAD

**Issue by ash2k** [atlassian/gostatsd#13]

**Comment by oryband** [comment]
i guess this equal to collectd's DERIVE metric? https://collectd.org/wiki/index.php/Data_source

**Comment by oryband** [comment]
any update on this one?

**Comment by ash2k** [comment]
Not sure about timestamp lag but gauge deltas should be straightforward to implement.

**Comment by aelse** [comment]
Thanks for opening the issue about this. It's been open a long time without movement on it so I'm going to close this off now.

Derive breaks down in many ways as you consider how time and space aggregations occur in statsd and the tsdb. It's an operation better left to the tsdb to perform.

If someone has a specific proposal for how to implement this we can look at it but I don't believe we're going to implement this ourselves and it's a feature that most tsdbs provide.
