### ISSUE TITLE
Ability to configure log level

### ISSUE THREAD

**Issue by CpuID** [atlassian/gostatsd#147]
https://github.com/atlassian/gostatsd/blob/1e74a750fea0915b9ebc64dc7f433fbfc93b76d8/cmd/gostatsd/main.go#L210-L212

Would be great to get this exposed as log levels rather than just `--verbose`, so we can turn off `INFO` in certain use cases. For example, using this package in a test suite to write statsd metrics to stdout.

**Comment by aelse** [comment]
Thanks for opening this issue. I don't think we'll add that level of config to logging.

If i understand your example, you have some application code emitting metrics and you want to validate (or see) what is being sent. You may be able to do what you need by injecting a mock statsd client in your application code to capture or expose what you need without needing to rely on logs from gostatsd. This is how we do this kind of check for our other services.
