### ISSUE TITLE
Look in to distroless / bezel

### ISSUE THREAD

**Issue by tiedotguy** [atlassian/gostatsd#158]
Might be worth looking in to this - https://github.com/GoogleCloudPlatform/distroless

**Comment by aidansteele** [comment]
Being a Golang binary, could we instead just do something like:

```
FROM scratch
COPY gostatsd /
CMD ["/gostatsd"]
```

and have a tiny binary that way?

**Comment by aelse** [comment]
I'm going to close this off as something we probably won't get to or want to maintain in addition to our other images.

An alpine image is already small enough for most people. Anyone who is concerned enough about that or the security surface of running in an alpine distro can easily build their own image.
