### ISSUE TITLE
google pubsub support

### ISSUE THREAD

**Issue by joemiller** [atlassian/gostatsd#159]
We recently added support for publishing to google pubsub to the carbon-relay-ng project, and consuming from pubsub to the go-carbon project. It's working well enough that I'm considering also adding pubsub support to gostatsd. Right now our pipeline looks like:

```
clients -> [gostatsd x 3 (ingestion tier)] -> [gostatsd x1 (aggregator)] -> [graphite-relay-ng] -> [google pubsub] -> [go-carbon]
```
Instead of having the gostatsd aggregator tier funnel into graphite-relay-ng over TCP we could have gostatsd publish in graphite format to pubsub, bypassing the TCP pipe to graphite-relay-ng. I suspect this could add a little more robustness to the pipeline. For example, right now when we update the graphite-relay-ng pods (it's a kubernetes deployment) there is a minute or so of lost metrics from the gostatsd tier. In this setup the pipeline would look like this:

```
clients -> [gostatsd x 3 (ingestion tier)] -> [gostatsd x1 (aggregator)] -> [google pubsub] -> [go-carbon]
```

In addition to gostatsd publishing to google pubsub in graphite format as in the example above, it might also be desirable for the gostatsd ingestion tier to publish statsd format to pubsub, such as:

```
clients -> [gostatsd x 3 (ingestion tier)] -> [google pubsub] -> [gostatsd x1 (aggregator)] -> [google pubsub] -> [go-carbon]
```

The goal being fewer dropped metrics when the gostatsd-aggregator process is restarted or dies.

Questions for gostatsd team:

1. Would the project consider PRs that added google-pubsub support?
2. If so, is there a recommended approach? In looking at the existing graphite-TCP backend code I think I would end up copying significant amounts of code to format the payload into graphite linemode format. So would it be better to add a configuration option to the existing graphite backend to toggle between TCP and google-pubsub? Or, create a new separate 'google pubsub' backend?

**Comment by ash2k** [comment]
1. I'll review PRs (when I have time), np here. Whether we want this or not - I think we do. However I'll let @tiedotguy decide, he runs it in prod.
2. If we want this functionality then I'd go with a separate backend and extract reusable pieces of code into a shared package - just like `pkg/backends/sender` which is used in multiple backends.

**Comment by joemiller** [comment]
@ash2k Thanks for the pointer to the sender.

**Comment by tiedotguy** [comment]
If it's useful, go for it!

I believe @ash2k is right with the approach - it should be a dedicated backend, with appropriate refactoring for code reuse.  Putting pub-sub in the middle is an interesting idea.  The one thing I'd call out as a hazard there is the lack of timestamps on statsd in the event of latency.  Unfortunately the pipeline doesn't lend itself well to handling that without a bunch of rework, so that may guide you away from it - or maybe it's not an issue, I'm not familiar enough with Google pub-sub.

I think you just need to make sure the CLA is signed if not already done.  I'm not too sure on that side of the process, I just do tech :)

**Comment by aelse** [comment]
Agreed on the approach.

re: CLA, please follow the instructions in the project README.

**Comment by joemiller** [comment]
Thanks for the feedback everyone!

You're right about timing, that may be an issue and I had not thought about
it yet. Pubsub does not guarantee delivery order, AFAIK. I don't think it
would be the issue in the case of publishing graphite line-mode (listed
above: `[gostatsd] -> [pubsub] -> [go-carbon]`) but it would be an issue in
the case of publishing statsd formatted metrics which lack a timestamp
(`[gostatsd ingest] -> [pubsub] -> [gostatsd-aggregator]`).

**Comment by aelse** [comment]
I think we answered this so I'm going to close off this ticket. Thanks for getting in touch, and let us know if you do decide to work on this!
