### ISSUE TITLE
[Feature] Option to disable internal metric flusher

### ISSUE THREAD

**Issue by nikkiattea** [atlassian/gostatsd#167]
Our gostatsd use case does not require the internal metrics generated from the server's InternalStatser. An option to disable the internal metrics produced here would be greatly appreciated!  https://github.com/atlassian/gostatsd/blob/2.3.0/pkg/statsd/statsd.go#L121-L125:
`// TODO: Make internal metric dispatch configurable`

**Comment by tiedotguy** [comment]
I **have** wanted to get to that TODO for a long time... every time I tinker with stuff locally.

**Comment by nikkiattea** [comment]
@tiedotguy It would be incredibly useful! I'm trying to think through some possible solutions, and trying to wrap my head around why the InternalStatser is required by many subsequent steps. Perhaps disabling just the metric collection?

**Comment by tiedotguy** [comment]
It's required by everything that needs to send metrics, hence it's injected everywhere.
