### ISSUE TITLE
please add influxdb backend

### ISSUE THREAD

**Issue by liuts** [atlassian/gostatsd#168]
influxdb is very popular and poweful  ,please add influxdb backend

**Comment by tiedotguy** [comment]
We have an open issue for this already (#14), but I haven't had much of a look at influx as there's not a large driver to implement it internally.

I understand it has both HTTP (and I assume non-HTTP based TCP) and UDP ingestion options.  What would the preferred method be?

**Comment by aelse** [comment]
Closing as duplicate.
