### ISSUE TITLE
Avoid LegacyNamespace (stats_counts dir)

### ISSUE THREAD

**Issue by ipeacocks** [atlassian/gostatsd#196]
I see that `Legacy Namespace` is enabled by default in `gostatsd`.

https://github.com/atlassian/gostatsd/blob/master/pkg/backends/graphite/graphite.go#L41

In original Etsy statsd there is an option:
```
  "graphite": {
    "legacyNamespace": false
  }
```
After that all counters are inside `stats` dir and it looks very logical and solid. Is there such option in `gostatsd` or I need to recompile `gostatsd`?

**Comment by tiedotguy** [comment]
I'm sorry I'm not completely understanding you.  That option can be turned off by having a toml option like:

```
[graphite]
legacy_namespace=false
```

I haven't used the Graphite backend extensively, so I don't know how closely it will match the namespaces you expect, however.  I think if you do a configuration as follows:
```
[graphite]
legacy_namespace=false
global_prefix=PPP # Defaults to "stats"
global_suffix=EEE # Defaults to ""
prefix_counter=CCC # Defaults to "counters"
```

You will get counters like:
- PPP.CCC.metric.countEEE
- PPP.CCC.metric.rateEEE

So if you leave them as default, with ```legacy_namespace=false```, you will get:
- stats.counters.metric.count
- stats.counters.metric.rate

Does this answer your question?

**Comment by ipeacocks** [comment]
Thanks. That's what I am looked for.

PS. I understand that this question is out of scope of this problem but...how to add custom percentile? By default there is 90 percentile and is it possible to add e.g. 95 percentile?

**Comment by tiedotguy** [comment]
No problem.

Yep, you can use the ```percent-threshold``` flag / option, I believe it's a space separated string.  Unfortunately it's not float based at present, so it can only go up to 99%ile, and not to 99.9 or higher.
