### ISSUE TITLE
Load Balancing and Scaling Out link is broken

### ISSUE THREAD

**Issue by ghmeier** [atlassian/gostatsd#200]
The current [Load balancing and scaling out](https://github.com/atlassian/gostatsd#load-balancing-and-scaling-out) link in the top section of the readme doesn't link to any valid documentation. Where should this link, I'm unable to find any related docs in the repo.

**Comment by tiedotguy** [comment]
I thought I had removed that reference in a [cleanup](https://github.com/atlassian/gostatsd/commit/df16c65c45edea57f1b09d18ab2b196522411095#diff-04c6e90faac2675aa89e2176d2eec7d8) a while ago.  The scale story is currently pretty poor - scale up, and/or manual sharding.  There are plans to add horizontal scaling, but it is likely to be a few months out at least.

The original documentation talked about having a LB, which then forwards on to a single large node, which is not actually scaling at all.

If you have an immediate need, you may find that [Veneur](https://github.com/stripe/veneur) is a suitable solution.  If you're already consuming metrics from gostatsd, then many of the aggregations names are different, which may cause some migration pain.

I will use this ticket to update the documentation, but sadly it will be to just remove the reference.

**Comment by ghmeier** [comment]
Nice, thanks for the update. I was mostly curious if there was documentation I was missing.
