### ISSUE TITLE
gometalinter install broken with golang:1.12.0

### ISSUE THREAD

**Issue by 2easy** [atlassian/gostatsd#231]
`go get` methond of installation for `gometalinter` is deprecated, and results with error when `make setup` is run inside golang:1.12.0 Docker container:

`gometalinter: error: failed to install the following linters: github.com/golang/lint/golint`

This should be fixed to recommended method of installation: https://github.com/alecthomas/gometalinter/blob/master/README.md#binary-releases

**Comment by tiedotguy** [comment]
Can you have another try? @aelse recently moved us to 1.12.3, which included moving to golangci-lint.

**Comment by tiedotguy** [comment]
Calling this done, as `gometalinter` is no longer involved.
