### ISSUE TITLE
Graphite tags support

### ISSUE THREAD

**Issue by TomMizrachi** [atlassian/gostatsd#233]
I'm trying to understand if you guys support the new graphite tagging system introduced in version 1.1.x

After going through the repo's intro doc I found out you guys don't support the graphite tagging format, as can be viewed here:
https://grafana.com/blog/2018/01/11/graphite-1.1-teaching-an-old-dog-new-tricks/

I would like to know if there are any plans for gostatsd to support graphite tags

**Comment by tiedotguy** [comment]
Hi

There was some discussion on #213 - my rough plan was to drop tags entirely in "graphite mode" (with a warning on startup), and there was some concern that there may be some explosion of file handles if we include tags.  The big problem is I don't know the graphite system well enough to assess the potential impact.

**Comment by TomMizrachi** [comment]
Can you please elaborate what about this concern? I don't see how adding tags might cause issues, since its just as adding tags for other endpoints.

**Comment by tiedotguy** [comment]
As I understand it, every unique metrics (ie, metric name + tagset) requires an open file handle, so cardinality can starve the system.

I don't know if this is a historical thing or not though, so it may well be a non-issue now.

**Comment by TomMizrachi** [comment]
I dont see how it has anything to do with gostatsd.
It is true that every unique metric is resembled as a file (whisper) in graphite, but the tag system does not create a whisper per tag - the tags are being stored in a different database, which is being queried when needed.

Here is a quote from the link I send in my first message:
```
At its core, the tagging system is implemented as a tag database (TagDB) alongside the metrics that allows them to be efficiently queried by individual tag values rather than having to traverse the metrics tree looking for series that match the specified query. Internally the tag index is stored in one of a number of pluggable tag databases, currently supported options are the internal graphite-web database, redis, or an external system that implements the Graphite tagging HTTP API. Carbon automatically keeps the index up to date with any tagged series seen.
```

**Comment by tiedotguy** [comment]
Ahh, sorry - I misunderstood this.  In the prior discussion, there was concern that baking tags in to the metric name could cause problems with lots of file handles (I don't know if it's a issue or not with modern Graphite).

I'll have a shot at adding it over the weekend, it would be nice to cleanup some of the outstanding Graphite issues :)

**Comment by tiedotguy** [comment]
@TomMizrachi - done! Please do raise a new issue if there's any problems - I don't have a good setup to really test it at scale.
