### ISSUE TITLE
Better explanation about flush-interval and expiry-interval

### ISSUE THREAD

**Issue by Turgon37** [atlassian/gostatsd#237]
Hello,
I've read the issue #213 because I'm in the same situation with two servers in active/passive. So when a server is switched I do not want the previous one continue to send metrics with 0 value.

My bucket time span is set to 10s. I want to delete any metrics that do not receive any value in a 10sec bucket. So I want to set the expiry-interval to 2s (for example), so I'm confused : is metrics flushed before they are deleted ?

Can you explain us what is the order between metrics flush and metrics deletion please ?

**Comment by tiedotguy** [comment]
Hi

The `MetricFlusher` attempts to runs every `flush-interval` - if it hasn't finished the last flush (this can happen if there's a lot of data to send to the backends, and can be monitored with the `flusher.total_time` metric), it will wait another full interval, so your actual flush interval will always be a multiple of the actual `flush-interval`.

When the `MetricFlusher` runs, it will synchronously aggregate, process (prepare to send), and reset (expire) metrics.  Reset will check if expiry is enabled (an `expiry-interval` of 0 will disable it entirely), then if the timestamp of the last received datapoint is older than the interval it will delete it.

The timestamp is the timestamp of the most recently received data (It should originate with the packet receive time).

As an example with a 2s expiry interval and 10s flush interval, if one metric comes in at T+3, and a different metric comes in at T+9, then at T+10 the service will flush and reset. It will delete the first metric (7 seconds old), but keep the second metric (1 second old).  Assuming no more metrics arrive, at T+20 it will send the second metric again, then delete it as it's now 11 seconds old.

You can also set a negative expiry value, which will mean that metrics always expire, which sounds like what you're after and is generally how I recommend running the service anyway, as persistence has bugs which can cause confusion (see #135)

Let me know if that clears things up!

**Comment by Turgon37** [comment]
Really thanks you, I've the related code https://github.com/atlassian/gostatsd/blob/984932b68727c2f30dacaf93e93a46742d850dc6/pkg/statsd/flusher.go#L61 and I've understandood your explanation.
I've put a monitoring point on the total flush time in order to be alerted when the time reached the flush interval
