### ISSUE TITLE
Revert #252-#254 and clarify retry documentation

### ISSUE THREAD

**Issue by tiedotguy** [atlassian/gostatsd#255]
The change in #252 and friends aren't needed, as it overlaps existing (but poorly documented) behavior.  The documentation should be clarified instead.

**Comment by MovieStoreGuy** [comment]
So the issue we had experienced is that ~8K worth of forwarders had an issues trying to send to the gostatsd receiver which meant there was a back up worth messages being retried and sent by each of them so our new connection count went from 0 --> ~900K due each forwarder performing retries. 

It wasn't clear that it was possible to disable retries completely and the intent of the PRs was to address that part. 

I'm happy to revisit this and update required docs but this was just to explain the intent of the PRs.

**Comment by tiedotguy** [comment]
I figured it was something like that.  I obviously don't know all the details, but my recommendation is to reduce the max request time, but don't kill retries completely (maybe to 1-2 seconds), as sometimes individual things fail.  I would also consider increasing the flush interval on the forwarder.

**Comment by adampetrovic** [comment]
Agree with you recommendation @tiedotguy - i'll revert and update our forwarders to reduce max request time.

**Comment by adampetrovic** [comment]
To clarify @tiedotguy. Setting `max-request-elapsed-time` to the `DefaultInitialInterval` (500ms) will effectively disable retries.

**Comment by tiedotguy** [comment]
Depends how fast things fails.  `1` is better because it looks more like a sentinel value (even though it isn't)

In theory I would say set it to `-1` to disable retries, because it's closer to a sentinel value.  Unfortunately we generally check to ensure it's >= 0, so it'd be a handful of sanity check changes as well.
