### ISSUE TITLE
Question statsd vs gostatsd

### ISSUE THREAD

**Issue by cjagus** [atlassian/gostatsd#271]
I'm started using gostatsd with a custom script for openldap metrics, difference I notice in b/w statsd vs gostatsd is missing `count` 

For example metrics from statsd: 

```total 24
drwxr-xr-x  6 carbon carbon 4096 May 24 09:56 ./
drwxr-xr-x 15 carbon carbon 4096 May 24 09:56 ../
drwxr-xr-x  2 carbon carbon 4096 May 24 09:56 bytes/
drwxr-xr-x  2 carbon carbon 4096 May 24 09:56 entries/
drwxr-xr-x  2 carbon carbon 4096 May 24 09:56 pdu/
drwxr-xr-x  2 carbon carbon 4096 May 24 09:56 referrals/
sets/openldap/statistics# cd bytes/
sets/openldap/statistics/bytes# ll
total 192
drwxr-xr-x 2 carbon carbon   4096 May 24 09:56 ./
drwxr-xr-x 6 carbon carbon   4096 May 24 09:56 ../
-rw-r--r-- 1 carbon carbon 201652 Oct 14 10:50 count.wsp
```

Metrics from gostatsd

```
-rw-r--r-- 1 carbon carbon 201652 Oct 14 11:37 referrals.wsp
-rw-r--r-- 1 carbon carbon 201652 Oct 14 11:37 pdu.wsp
-rw-r--r-- 1 carbon carbon 201652 Oct 14 11:37 entries.wsp
-rw-r--r-- 1 carbon carbon 201652 Oct 14 11:37 bytes.wsp
sets/openldap/statistics#
```

gostatsd configs

```
[graphite]
address = "graphite:2003"
legacy_namespace = "false"
global_prefix = "stats.ldap.ldap01"

mode = 'basic'
```
Did I miss any configs for gostatsd?.

**Comment by tiedotguy** [comment]
Hi

What is the type of the metric you're emitting?  From the `sets` in your path, I'm guessing it's a set, but I'd like to make sure.  A set metric won't have a `.count` suffix, and it's also (probably) the wrong metric type based off the names - if you give the inputs of `alice`, `bob`, `carol`, `bob` to a set, the emitted value will be 3 (because there's 3 distinct values).

**Comment by tiedotguy** [comment]
@cjagus, closing this off for now, feel free to re-open it if you need clarification.  Please include the actual metric data you're sending as well if you need to.
