### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by radinv** [atlassian/gostatsd#293]
Hi !
I'm build bin file.
go version go1.13.3 linux/amd64

**I'm try run:**
./gostatsd --config-path /etc/gostatsd/config.toml

**config:**
[graphite]
address = "localhost:2003"
dial_timeout = '5s'
write_timeout = '30s'

mode = 'tags'

global_prefix = 'stats'
global_suffix = ''

prefix_counter = 'stats_counts'
prefix_timer = 'timers'
prefix_gauge = 'gauges'
prefix_sets = 'sets'

**Errors:**

INFO[0000] Starting server                              
INFO[0000] No cloud provider specified                  
INFO[0000] [graphite] address=localhost:2003 dialTimeout=5s writeTimeout=30s counterNamespace=stats.stats_counts timerNamespace=stats.timers gaugesNamespace=stats.gauges setsNamespace=stats.sets globalSuffix= mode=tags 
INFO[0000] Initialised backend "graphite"               
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x1798bf7]

goroutine 1 [running]:
github.com/atlassian/gostatsd/pkg/statsd.NewCloudHandler(0x0, 0x0, 0x20a7320, 0xc0000b83c0, 0x20dcba0, 0xc000122480, 0x0, 0x0, 0x0, 0x0, ...)
        /gostatsd/pkg/statsd/handler_cloud.go:175 +0xd7
github.com/atlassian/gostatsd/pkg/statsd.(*CloudHandlerFactory).NewCloudHandler(...)
        /gostatsd/pkg/statsd/handler_cloud.go:120
github.com/atlassian/gostatsd/pkg/statsd.(*Server).RunWithCustomSocket(0xc00032d680, 0x209c320, 0xc00034f240, 0xc0003e4750, 0x0, 0x0)
        /gostatsd/pkg/statsd/statsd.go:152 +0x1042
github.com/atlassian/gostatsd/pkg/statsd.(*Server).Run(0xc00032d680, 0x209c320, 0xc00034f240, 0xc00034f240, 0xc000385a80)
        /gostatsd/pkg/statsd/statsd.go:61 +0x6b
main.run(0xc000303b00, 0x0, 0x0)
        /gostatsd/cmd/gostatsd/main.go:78 +0x19b
main.main()
        /gostatsd/cmd/gostatsd/main.go:55 +0x158

**Comment by tiedotguy** [comment]
Looks like a bug introduced with the recent cloudprovider work, I'll get it fixed shortly.

**Comment by tiedotguy** [comment]
Should be sorted now, sorry for that @radinv
