### ISSUE TITLE
When statsd wait metric it send 0 to backend

### ISSUE THREAD

**Issue by radinv** [atlassian/gostatsd#296]
When statsd wait metric it send 0 to backend (go-carbon)
<img width="869" alt="image" src="https://user-images.githubusercontent.com/55874175/76004093-05d73600-5f1a-11ea-8fd7-a34b5fd3a2fc.png">

How I can don't send 0 to backend?

**Comment by radinv** [comment]
**my config:**
[graphite]
address = "localhost:2003"
dial_timeout = '5s'
write_timeout = '30s'

mode = 'legacy'

global_prefix = 'stats'
global_suffix = ''

prefix_counter = 'counters'
prefix_timer = 'timers'
prefix_gauge = 'gauges'
prefix_sets = 'sets'


With this config stated send 0 every 1 second. 
How it is if by default every 30 sec?

**Comment by tiedotguy** [comment]
It's the interaction of two separate parts - flush interval and metric expiry.

The flush interval is how often metrics are aggregated and sent upstream, and is 1 second by default.  The expiry interval is how long a metric needs to receive no data before it stops being sent upstream.

If you were to not send and metrics for 30 seconds, you would see your last value, 29 zeros, and then it would stop sending.

When I look at your graph, I can see there are periods of at least 30 seconds where the value appears to be 0 (I'm assuming all your non-zero values are > 400, and not 1 or 2 where it may not be visible on the graph).  The rendered interval also appears to be 10 seconds. This makes me suspect there's also zeros being added on display, but that's speculation.

**Comment by radinv** [comment]
Thanks for the explanation, It's working!
