### ISSUE TITLE
Per metric-type expiry interval

### ISSUE THREAD

**Issue by radinv** [atlassian/gostatsd#300]
How I can send to back the previous value, if the gauge is not updated at the next flush?

**Comment by tiedotguy** [comment]
They should send the previous value if the expiry is non-zero (from #296).  As present there's no notion of different expiry intervals for different metric types, so it does mean you'll get 0s from your counters if you set that.

If you want per-metric-type expiry intervals as a feature request it should be fairly trivial to add - but it would be just per type, and not have any configuration on a per metric name or anything.

**Comment by radinv** [comment]
Yes, it will be good. I want customize expiry-interval per-metric-type.

**Comment by tiedotguy** [comment]
I'll leave it for a few days in case anyones interested in picking this up, otherwise I'll do it at some point.
