### ISSUE TITLE
how enable Histogram?

### ISSUE THREAD

**Issue by radinv** [atlassian/gostatsd#301]
Hi, how I can enable histogram for metrics?
I try test it:
`echo "my_prefix.my_metrics.some_metric:100|ms;gsd_histogram:1_10_100_1000_10000"  | nc -u 127.0.0.1 8125`

Can I enable histogram for all metrics after` my_prefix.my_metrics` ?

**Comment by tiedotguy** [comment]
That's not the format for tags, gostatsd speaks the dogstatsd variation for tagging, which looks like:
```
my_prefix.my_metrics.some_metric:100|ms|#gsd_histogram:1_10_100_1000_10000
```

Note the `|#` rather than a `;` to designate the start of tags.

This will result in the following metrics (using the stdout backend):
```
INFO[0170] stats.timers.my_prefix.my_metrics.some_metric.gsd_histogram.1_10_100_1000_10000.s.127.0.0.1.histogram.le:+Inf 1 1586872106
INFO[0170] stats.timers.my_prefix.my_metrics.some_metric.gsd_histogram.1_10_100_1000_10000.s.127.0.0.1.histogram.le:1 0 1586872106
INFO[0170] stats.timers.my_prefix.my_metrics.some_metric.gsd_histogram.1_10_100_1000_10000.s.127.0.0.1.histogram.le:10 0 1586872106
INFO[0170] stats.timers.my_prefix.my_metrics.some_metric.gsd_histogram.1_10_100_1000_10000.s.127.0.0.1.histogram.le:100 1 1586872106
INFO[0170] stats.timers.my_prefix.my_metrics.some_metric.gsd_histogram.1_10_100_1000_10000.s.127.0.0.1.histogram.le:1000 1 1586872106
INFO[0170] stats.timers.my_prefix.my_metrics.some_metric.gsd_histogram.1_10_100_1000_10000.s.127.0.0.1.histogram.le:10000 1 1586872106
```

The histogram buckets must be specified on every single metric sent that is intended to use the system.

**Comment by radinv** [comment]
I try it, but I have default metrics only, not histogram.

`while true; do echo "test.metric.pull.fail:500|ms|#gsd_histogram:1_10_100_1000_10000" | nc -u 127.0.0.1 8125; done`


```
tcpdump -A -i any dst port 2003 | grep "test.metric"
stats.timers.test.metric.pull.fail.lower 500.000000 1586873607
stats.timers.test.metric.pull.fail.upper 500.000000 1586873607
stats.timers.test.metric.pull.fail.count 1410 1586873607
stats.timers.test.metric.pull.fail.count_ps 141.000146 1586873607
stats.timers.test.metric.pull.fail.mean 500.000000 1586873607
stats.timers.test.metric.pull.fail.median 500.000000 1586873607
stats.timers.test.metric.pull.fail.std 0.000000 1586873607
stats.timers.test.metric.pull.fail.sum 705000.000000 1586873607
stats.timers.test.metric.pull.fail.sum_squares 352500000.000000 1586873607
stats.timers.test.metric.pull.fail.count_90 1269.000000 1586873607
stats.timers.test.metric.pull.fail.mean_90 500.000000 1586873607
stats.timers.test.metric.pull.fail.sum_90 634500.000000 1586873607
stats.timers.test.metric.pull.fail.sum_squares_90 317250000.000000 1586873607
stats.timers.test.metric.pull.fail.upper_90 500.000000 1586873607
stats.timers.test.metric.pull.fail.count_99 1396.000000 1586873607
stats.timers.test.metric.pull.fail.mean_99 500.000000 1586873607
stats.timers.test.metric.pull.fail.sum_99 698000.000000 1586873607
stats.timers.test.metric.pull.fail.sum_squares_99 349000000.000000 1586873607
stats.timers.test.metric.pull.fail.upper_99 500.000000 1586873607
```

what am I doing wrong?

My config:

```
[graphite]
address = "localhost:2003"
dial_timeout = '5s'
write_timeout = '30s'

mode = 'legacy'
expiry-interval = '1'
flush-interval = '5'
global_prefix = ''
global_suffix = ''

prefix_counter = 'stats_counts'
prefix_timer = 'stats.timers'
prefix_gauge = 'stats.gauges'
prefix_sets = 'stats.sets'
```

From gestated.service:

`ExecStart=/usr/local/bin/gostatsd --config-path /etc/gostatsd/config.toml --metrics-addr 0.0.0.0:8125 --ignore-host --percent-threshold '90 99' --expiry-interval '-1s' --flush-interval '10s'`

**Comment by tiedotguy** [comment]
That should be sufficient, can you provide the output of `/usr/local/bin/gostatsd --version`?

**Comment by radinv** [comment]
Version: 20.1.1 - Commit: feab53b - Date: 2020-03-04-07:06

**Comment by tiedotguy** [comment]
That will be it - bucketed histograms were added in 20.3.0, you'll need to update your version :)

**Comment by radinv** [comment]
Ok, I'l build it!

**Comment by tiedotguy** [comment]
Something else to note - with graphite in legacy mode it won't work properly, as legacy doesn't emit tags.  Tags are still calculated and processed, but the actual data sent to graphite ignores the tag data, so you will only see `stats.timers.test.metric.pull.fail` being sent multiple times, rather than multiple times with different tags.

That's not the issue that was happening here, but it will happen after you update the version, as the `le` tag will be discarded.

**Comment by tiedotguy** [comment]
Calling this one resolved, but feel free to re-open it, or raise a fresh issue if you have any further queries!
