### ISSUE TITLE
Coveralls needs to be advisory only

### ISSUE THREAD

**Issue by tiedotguy** [atlassian/gostatsd#311]
At some point coveralls was added in a ratchet configuration which means coverage is only ever allowed to improve, or merges are blocked.  There also appears to be issues where the following situation occurs:

1. commit some code, coverage goes down
2. commit some coverage, coverage goes up
3. squash and merge, coverage goes down, master is "red".  That's the state of 56120725587cf82aac5c7e1b0501a8967af45fb4 (Current master as of raising this issue)

I'm not certain if this is the actual sequence of events, but it looks like it might be based on recent commits.

Coveralls should be changed to be advisory only.

**Comment by thombergs** [comment]
I don't know how coveralls was enabled for this repo, but I disabled it now:

![image](https://user-images.githubusercontent.com/1363578/85358173-6b494400-b556-11ea-8ae2-f6c354912bee.png)

**Comment by tiedotguy** [comment]
Thanks @thombergs !
