### ISSUE TITLE
Saturation metrics for Gostatsd

### ISSUE THREAD

**Issue by MovieStoreGuy** [atlassian/gostatsd#312]
Looking at the metrics https://github.com/atlassian/gostatsd/blob/master/METRICS.md, I can't see anything that would indicate saturation of the service.

I was thinking we can look at capturing remaining request (the current semaphore count) as metric for the statsd receiver so that we can track how much headroom we can add to the `max-requests` because I suspect we are walking into this problem but none of the metrics currently show it.

Do you have any thoughts on this @tiedotguy @ash2k ?

**Comment by tiedotguy** [comment]
Sure, drop a `stats.ChannelStatsWatcher` on the semaphore, but be aware that that's 6 new metrics, so shouldn't be on the forwarder path.

**Comment by tiedotguy** [comment]
I dug in to this a bit more, `max-requests` is only about outgoing requests.

Incoming requests are unbound at the http layer (aka no rate limiting), with back pressure that starts at the channel write at `BackendHandler.DispatchMetricMap`.  The channel that backs this (`worker.metricMapQueue`) doesn't have a `ChannelStatsWatcher`, although the one that processes metrics (`worker.metricsQueue`) does.

`worker.RunMetrics` should have a CSW added to it for `worker.metricMapQueue`, which would expose if there's back pressure occurring.

**Comment by MovieStoreGuy** [comment]
I've picked this up and will have a PR shortly.

**Comment by MovieStoreGuy** [comment]
Fixed by: https://github.com/atlassian/gostatsd/pull/319
