### ISSUE TITLE
Coveralls is still sad

### ISSUE THREAD

**Issue by tiedotguy** [atlassian/gostatsd#314]
After completely disabling coveralls on the backend in #311, we now can't build because coveralls doesn't know about the repo.

I'm not sure if we should just disable coveralls in the build, or what our options are to enable coveralls but make it non-ratcheting.

**Comment by MovieStoreGuy** [comment]
Currently chasing up internal owners to address this.

**Comment by thombergs** [comment]
Hmmm, I guess we have two options:

1. enable coveralls again and don't make it a required status check 
2. leave coveralls disabled and remove coveralls from the build process

Which should we try?

**Comment by thombergs** [comment]
I went for option 1 now. I enabled coveralls again, and checked that it isn't a required check for Github. Merges shouldn't be blocked by it.

Let me know if that solves it.

**Comment by tiedotguy** [comment]
1 is definitely preferred - coverage is absolutely useful.  Thanks!

**Comment by adampetrovic** [comment]
What needs to happen to get master to build properly?

**Comment by tiedotguy** [comment]
I was hoping a rebuild would do it.

The message we're getting is:
```
goveralls -coverprofile=coverage.out -service=travis-ci
Bad response status from coveralls: 422
{"message":"Couldn't find a repository matching this job.","error":true}
```

I'll try pushing through a dummy commit, since it mentions "job", if the rebuild was the same job that might be the problem.

**Comment by tiedotguy** [comment]
Still seems unhappy. No idea how anything in coveralls works - can you take another look, @thombergs ?

**Comment by tiedotguy** [comment]
Failure can be seen at the end of the build at https://travis-ci.org/github/atlassian/gostatsd/builds/701896125

**Comment by adampetrovic** [comment]
@tiedotguy is the answer to move `make coveralls` into an `after_script` block so that it runs but doesn't affect the build result?

**Comment by MovieStoreGuy** [comment]
I have gone into coveralls and reenabled for the time being, let see if this improves things.

**Comment by tiedotguy** [comment]
Ok - my branch build succeeded.  I'll go remove some tests and see if it gets upset at reduced coverage.

**Comment by MovieStoreGuy** [comment]
I suspect it worked due to the fact that it has started from a "fresh" state.

However, I think Adam's approach would be the way forward.

**Comment by tiedotguy** [comment]
I don't think it's a build result thing is the problem - the build failed because coveralls failed, but earlier PRs were blocked because coveralls showed a reduction as a distinct check.  The build was still a success.

**Comment by tiedotguy** [comment]
![image](https://user-images.githubusercontent.com/29549188/85669384-1e56a080-b703-11ea-9d7d-0443bdb0ddf0.png)

I don't have the example of a failure because I added coverage, but it was coverage/coveralls blocking, not continuous-integration/travis-ci/pr

**Comment by tiedotguy** [comment]
Ok, so things aren't ideal, but I think it's workable now.  I believe the repo is misconfigured in some way that I can't see, but it effectively cancels out the coveralls issue.

Near as I can figure it, coveralls seems to be getting confused because we build twice (travis-ci/pr and travis-ci/push).  One of the builds is compared against master, which may cause a reduction (and block the merge), and then the second build is compared against the first, which says they're equal, and allows the merge.  If coverage fails, then I think a rebuild will make it say the coverage is equal, and reallow merging.

I'm not certain how accurate this assessment is, but I think it's ok to close off for now.  If a hard block comes in at some point, I'll probably just remove coveralls.

@adampetrovic - FYI, I've tagged 22.0.0 as a release, there should be a docker image in 5-10 minutes.
