### ISSUE TITLE
#290 introduces flusher bug that causes internal metrics to not be sent

### ISSUE THREAD

**Issue by adampetrovic** [atlassian/gostatsd#316]
CC @ash2k 

We just upgraded our production release from 20.3.1 to 22.0.0 and noticed that we stopped sending internal metrics about backend events, specifically: https://github.com/atlassian/gostatsd/blob/979ab8493471cbea7625d07fcf48600209bf45a3/pkg/backends/datadog/datadog.go#L146-L151

A debug session shows that the `flushed` channel is never called on a flush.

I did a git bisect and found the offending commit is from https://github.com/atlassian/gostatsd/pull/290

**Comment by tiedotguy** [comment]
The `constructServer` creates the CI/CP and backends, and `main.run` starts them.  It's only later in `RunWithCustomSocket` that we create a `Context` with an attached `Statser` for `Runnable`s.

The result is that when we ask the `Context` for a `Statser`, we get back the `nullStatser`.

https://github.com/atlassian/gostatsd/pull/290#discussion_r406574820 is the justification for the change

> Server receives backends as a parameter - it is not the owner, it didn't create them. So it should not be managing their lifecycle. That is why I moved this up one level into whatever constructs the Server. Same applies to CachedInstances and cloud providers.

We would have lost CP metrics as well, but they're no longer in the system, so weren't noticed.

We need to delay running until we have a Context.

**Comment by ash2k** [comment]
Yeah, a review is needed for all the places which take a statser for the internal metrics. I've noticed that things are inconsistent but the PR was too big already. I've changed some places I guess, but haven't thoroughly checked every statser usage. I'll fix this.

In the mean time, can someone test  #304 to prevent it from rotting? :)
