### ISSUE TITLE
Document version system used

### ISSUE THREAD

**Issue by KateGo520** [atlassian/gostatsd#335]
I found that this project already [supports Go modules](https://github.com/atlassian/gostatsd/blob/master/go.mod). But sadly, the [tags](https://github.com/atlassian/gostatsd/tags) doesn't follow [Semantic Versioning](https://semver.org), which means that all tags of this project will be ignored by Go modules and replaced by pseudo-versions, go get acts weirdly when tags are not in that form. It would be great to have the tagged release be named in the format vX.X.X format so that go mod can read it. 
```
	github.com/atlassian/gostatsd v0.0.0-20200807124358-416562efa755
```
Else the mod file shows something like `github.com/atlassian/gostatsd v0.0.0-20200807124358-416562efa755` which is not very readable and difficult to upgrade. It’s hard to verify which version is in use. This is not conducive to version control.

So, I propose this project to follow Semantic Versioning in future versions. For example, `v1.0.1`, `v2.0.0`, `v3.1.0-alpha`, `v3.1.0-beta.2`etc.

**Comment by KateGo520** [comment]
@tiedotguy  @ash2k  Could you help me review this issue? Thx :p

**Comment by tiedotguy** [comment]
Well bother.  This sounds more like an issue with go's interpretation of semvers. From [Is “v1.2.3” a semantic version?](https://semver.org/#is-v123-a-semantic-version): the v is common (in english), but not actually part of semver.

That being said, tagging is done manually, so doesn't really make a difference, we can add a `v` prefix going forward 🤷

We have a release pending which I just haven't got to releasing (28.2.0), so I'll start with that.

**Comment by tiedotguy** [comment]
@MovieStoreGuy @adampetrovic FYI: we're prefixing tags with `v` now if you release anything.

**Comment by adampetrovic** [comment]
This should only impact cases where you want to use gostatsd as a library. We could still omit the 'v' prefix for docker image tags.

**Comment by tiedotguy** [comment]
Does docker care about a `v` prefix? We use the git tag directly as the docker tag.

**Comment by adampetrovic** [comment]
No it doesn't. I've never seen any of the major docker images use "vX.Y.Z" as the tagging format.

**Comment by tiedotguy** [comment]
It's less about consistency and more about being lazy and not updating build scripts :)

**Comment by KateGo520** [comment]
I get trouble again. 
```
$go get github.com/atlassian/gostatsd@v28.2.0
go get github.com/atlassian/gostatsd@v28.2.0: github.com/atlassian/gostatsd@v28.2.0: invalid version: module contains a go.mod file, so major version must be compatible: should be v0 or v1, not v28
```
It seems the module path should be "github.com/atlassian/gostatsd/v28":
The github.com/atlassian/gostatsd uses [Go modules](https://github.com/golang/go/wiki/Modules) and the current release stream version is **v28**. It need comply with the specification of "Releasing Modules for v2 or higher" available in the Modules documentation and enforced since the most recent versions of Go. The module path should be "github.com/atlassian/gostatsd/v28". Quoting the specification:
> A package that has opted in to modules _must_ include the major version in the import path to import any v2+ modules
> To preserve import compatibility, the go command requires that modules with major version v2 or later use a module path with that major version as the final element. For example, version v2.0.0 of _example.com/m_ must instead use module path _example.com/m/v2_.
https://github.com/golang/go/wiki/Modules#releasing-modules-v2-or-higher

This is the downstream repo:
https://github.com/search?q=%22github.com%2Fatlassian%2Fgostatsd%22+filename%3Ago.mod&type=Code

Perhaps this matter needs careful consideration.

**Comment by adampetrovic** [comment]
`import "github.com/atlassian/gostatsd/v28"` just has such a nice ring to it, doesn't it? 🤦

**Comment by tiedotguy** [comment]
gostatsd is an application first and a library second, and we burn major versions like they're free.

If I'm understanding this correctly, it now goes from free to very very expensive (changing imports in over half the source files in the project every time we bump, moving files to new directories?).

> "Packages intended for public use should try to maintain backward compatibility as they evolve. The Go 1 compatibility guidelines are a good reference here: don't remove exported names, encourage tagged composite literals, and so on. If different functionality is required, add a new name instead of changing an old one. If a complete break is required, create a new package with a new import path."

I have no intention of doing any of that at this point of time.  That may change once the majority of the code is migrated to `internal`, but there's no push to do that at present - I'm trying to maintain surface area, not reduce it.

Is my understanding correct?  If so, I'm ok with deleting the tag so as not to confuse future attempts to `go get`, and continuing how we did it before, leaving it up to anyone who wants to consume us as a library to manage it via commits, with the understanding that it's semantic versioning of the API (semver), but not packages (go's semver).

**Comment by adampetrovic** [comment]
I would rather imports looking like `github.com/atlassian/gostatsd v0.0.0-20200807124358-416562efa755` that the overhead of maintaining this project as a library to golang's standards (which is a secondary concern).

**Comment by tiedotguy** [comment]
I'll submit a PR updating the `README.md` to reflect this.

**Comment by KateGo520** [comment]
Thank you for your feedback. @tiedotguy  @adampetrovic
