### ISSUE TITLE
sending metrics to backend failed error messages

### ISSUE THREAD

**Issue by rtkmhart** [atlassian/gostatsd#34]
I'm trying out this version of gostatsd, it looks really promising. When running gostatsd with either of these startup commands:

`gostatsd --backends graphite --config-path ./config.toml --flush-interval 10s --verbose`

or

`gostatsd --backends "statsdaemon" --config-path ./config.toml --verbose`

I see this error message every time it flushes the metrics, yet they do show up in graphite (tcpdump confirms it). I've exhausted my very limited knowledge of go trying to figure out why https://github.com/atlassian/gostatsd/blob/master/statsd/flusher.go#L113 is logging an error. Any ideas?

**Comment by ash2k** [comment]
@rtkmhart could you paste the full error message? Also contents of config file might be useful too.

**Comment by rtkmhart** [comment]
whoops, somehow missed the most important part. Error in both cases is just this one line:

`ERRO[17794] Sending metrics to backend failed: <nil>`

With the `--backends graphite` the config file is (IP's changed to protect the innocent):
`
[graphite]
    address = '10.1.2.3:2003"
`

And the `--backend statsdaemon` config file:

`
[statsdaemon]
    address = "10.1.2.4:8125"
`

**Comment by ash2k** [comment]
Please ignore this error, it is a bug in the code that prints errors. I'll fix it shortly.

**Comment by rtkmhart** [comment]
Thanks for the quick response!
