### ISSUE TITLE
Address how aggregations deals with large numbers

### ISSUE THREAD

**Issue by MovieStoreGuy** [atlassian/gostatsd#342]
As part of https://github.com/atlassian/gostatsd/pull/333, it was identified that it is possible for aggregations to produce large numbers that can not be expressed as within json and for the time being causing dataloss for the datadog backend. 

I'd like to suggest that we look at clipping values to closest representative value within the aggregator:
- Inf+ --> float.Max
- Inf- --> float.Min
- NaN --> 0 

Or at least, allow this to be a configuration that would allow for the aggregator to drop or clip since.

On the same vein, users shouldn't be sending values that would result in one of these however, it has been seen and with larger aggregation periods, I suspect we may actually see this happen more often.

Curious to know your thoughts @tiedotguy

**Comment by tiedotguy** [comment]
Is this done now with the change from @digitalpoetry , @MovieStoreGuy ?

**Comment by MovieStoreGuy** [comment]
Yeah, I think so :)
