### ISSUE TITLE
Variable test coverage in backends.Sender 

### ISSUE THREAD

**Issue by tiedotguy** [atlassian/gostatsd#345]
There's some more [variable test coverage](https://coveralls.io/builds/33905842) in backends.Sender.

**Comment by pkruk** [comment]
This looks like fun ;) I will start working on that :)!

**Comment by tiedotguy** [comment]
Awesome! It doesn't seem to show in the link in the issue, but I believe the problem is [here](https://github.com/atlassian/gostatsd/blob/master/pkg/backends/sender/sender.go#L39-L41), where sometimes stream is nil, sometimes it's not nil.  If the coverage check saw it get ran in one build, and then in the next build it gets skipped, it shows as a failure.

The hardest part of this is typically figuring out how to reliably trigger the code path in a test.

**Comment by pkruk** [comment]
I have slight problems with this issue, so if anyone will find the solution do not hesitate ;) 
Firstly I was thinking about mocking somehow this buffer but it's not so easy for me ;)

**Comment by tiedotguy** [comment]
My approach would be to work backwards from the desired state.

1. `stream` must not be `nil` when `Run` exits
2. The for loop from 45-85 has no `break`, so `Run` only exits at lines 61 and 81.  Line 61 is more about the error path, so we'll ignore that for now and look at line 81.  We want to `innerRun` to return with both a cancelled context error, and a valid `*Stream`.
3. `innerRun` only checks `context.Done()` when `stream` is nil, which means that it's impossible for `innerRun` to return both a cancelled context and a stream, so we backtrack to line 61
4. The for loop is entered if `Sender.ConnFanctory()` returns an error, which we can force easily.
5. The first time through, `stream` will be `nil`, so it enters reads a `Stream` from `Sink`, then re-enters the loop
6. The second time through, `stream` will not be nil, so it reads `streamCancel` from `stream.Ctx`, and waits for:
6.1. the main context to be cancelled (this is our target)
6.2 a new `Stream` from `Sink` (this will never fire, because `Sink` is `nil`)
6.3. the stream context to be cancelled (this is bad, it cleans up the stream)
6.4. the 1 second timer to fire

So this gives us an approach:
1. Create a `ConnFactory` that always fails, with a context that we give it
2. Send a `Stream` to the Sink, which indicates "success" when the `Cb` is called
3. Cancel the context we provided
4. Wait for `Cb` to be called (or a general timeout, because if it doesn't call us, we don't want to wait until the test times out).

When we look at the test file though, we find almost this exact process already exists in `TestSendCallsCallbacksOnMainCtxDone`.  Clearly something isn't working quite as expected.

I can explain the rest, but if you'd like to take this as a hint and try working through it further, I'll give you that opportunity (with a couple of extra hints (hopefully) hidden below).

<details>
  <summary>Hint 1</summary>
<a href="https://golang.org/doc/effective_go.html#channels">"Channels" section in Effective Go.</a>
</details>

<details>
  <summary>Hint 2</summary>
... If the channel is unbuffered, the sender blocks until the receiver has received the value. If the channel has a buffer, the sender blocks only until the value has been copied to the buffer ...
</details>

**Comment by tiedotguy** [comment]
@pkruk - I've put in a PR with the fix, and an explanation of what triggered it.  You may find Kavya Joshis [talk](https://www.youtube.com/watch?v=KBZlN0izeiY) on channels to be interesting, as it goes in to the schedulers behavior when channels are buffered/full/unbuffered.  I recommend all her content.

**Comment by pkruk** [comment]
nice thanks! will watch it definitely!
