### ISSUE TITLE
Move the pool namespace to internal/pool

### ISSUE THREAD

**Issue by tiedotguy** [atlassian/gostatsd#347]
This is an isolated bit of code that can and should be moved out of the public interface.

**Comment by pkruk** [comment]
I can take a look on that :)

**Comment by tiedotguy** [comment]
I haven't been keeping up with what's happening with the hacktoberfest drama and opt-in/opt-out, but if you're interested doing it under that, I'll get whatever is needed done on the repo to make it valid.

**Comment by pkruk** [comment]
yeah sure, I'm just the python guy who was looking for some golang first_issue stuff:P I want to learn golang in a hard way ;) Today after work I think I will push a PR for that.

**Comment by tiedotguy** [comment]
Fair enough - if it would be helpful for your learning, I'm happy to go in to some of the background/why behind the issue?

**Comment by pkruk** [comment]
I create this PR, and tagged in a topic this issue:
https://github.com/atlassian/gostatsd/pull/348
If you spot sth, please do not hesitate to tag me, so I will fix it :)
