### ISSUE TITLE
make: *** [Makefile:106: docker] Error 1

### ISSUE THREAD

**Issue by 0AlexZhong0** [atlassian/gostatsd#356]
## What is the error
```
docker pull golang:1.13.6  
1.13.6: Pulling from library/golang
Digest: sha256:04bdcb522081df9c95e5888ada7da60da18fd0b0eae9423fdf05a477e0894352
Status: Image is up to date for golang:1.13.6
docker.io/library/golang:1.13.6
docker run \
        --rm \
        -v "":"/gopath" \
        -w "/gopath/src/github.com/atlassian/gostatsd" \
        -e GOPATH="/gopath" \
        -e CGO_ENABLED=0 \
        golang:1.13.6   \
        go build -o build/bin/linux/gostatsd -ldflags "-s -X main.Version=$(git describe --abbrev=0 --tags) -X main.GitCommit=$(git rev-parse --short HEAD) -X main.BuildDate=$(date +%Y-%m-%d-%H:%M)" github.com/atlassian/gostatsd/cmd/gostatsd
can't load package: package github.com/atlassian/gostatsd/cmd/gostatsd: cannot find package "github.com/atlassian/gostatsd/cmd/gostatsd" in any of:
        /usr/local/go/src/github.com/atlassian/gostatsd/cmd/gostatsd (from $GOROOT)
        /gopath/src/github.com/atlassian/gostatsd/cmd/gostatsd (from $GOPATH)
make: *** [Makefile:106: docker] Error 1
```

## Reproducing the error
By following the `README` documentation, I ran `make setup` -> `make build`. `make run` which uses `stdout` as the backend works for my machine. However, after I ran `make run-docker`, the above error occurs.

My operating system is POP_OS 20.04, the version of `go` is 1.13.6, `docker` is 19.03.13.

## What have I tried
Because my `GOPATH` is `/home/alex/go`, so I tried changing the `GP` variable in `Makefile` from `/gopath` to `/home/alex/go`, then I ran `make run-docker` again and the same error occurs.

**Comment by tiedotguy** [comment]
From `-v "":"/gopath"`, it looks like you don't have a GOPATH set in your shell.  The result of this is no `/gopath` volume being mounted at all, and the source not being found.  `$GP` is the path inside docker, not outside.

Can you double check that `GOPATH` is an exported variable?

**Comment by 0AlexZhong0** [comment]
You are right, that's where the issue is. `go env GOPATH` yields `/home/alex/go`, but `echo $GOPATH` gives an empty string, so it looks like I have to have `GOPATH` as an exported variable in the shell instead.

The solution is then:
- Edit $GOPATH as an environment variable and point it to $HOME/go. In Windows, can do it through the GUI menu. In Linux or Mac, we can do it by adding `export GOPATH=$HOME/go` in `~/.bashrc` or `~/.zshrc`
