### ISSUE TITLE
build_gostatsd_1 exited with code 1

### ISSUE THREAD

**Issue by 0AlexZhong0** [atlassian/gostatsd#357]
After running `docker-compose up --build` in the `build` directory, I get this error causing `gostatsd` to exit:

`gostatsd_1  | time="2020-11-08T08:22:56Z" level=fatal msg="Error while parsing configuration: open /etc/gostatsd/docker-compose.toml: no such file or directory"`. 

I believe the `docker-compose.toml` is supposed to be in the docker container file system, right? Yet I don't think there is a setup anywhere that adds a `docker-compose.toml` file to the path `/etc/gostatsd`.

**Comment by tiedotguy** [comment]
I missed this issue somehow, my apologies.

At one point we had sample toml files, but they got removed in some shuffling.  This is something that will be addressed by #264 when that gets done.

If you have any questions about the configuration, please raise another issue and I'll get you going.
