### ISSUE TITLE
Build failed for CentOS-7

### ISSUE THREAD

**Issue by fred-cm** [atlassian/gostatsd#364]
# cat /etc/redhat-release
CentOS Linux release 7.8.2003 (Core)
# head CHANGELOG.md
29.0.0
------
- Support for ARM64 docker image
- Test changes and fixes to improve coverage
- Internal code refactoring to reduce surface area
- Refactor lexer to improve memory usage

28.3.0
------
- Rather than dropping data points, the Datadog backend will coerce non-numeric values resulting from aggregation to numeric.
# go version
go version go1.15.5 linux/amd64
# make build
gofmt -w=true -s $(find . -type f -name '*.go' -not -path "./vendor/*" -not -path "./pb/*")
goimports -w=true -d -local github.com/atlassian/gostatsd $(find . -type f -name '*.go' -not -path "./vendor/*" -not -path "./pb/*")
flag provided but not defined: -local
usage: goimports [flags] [path ...]
  -d=false: display diffs instead of rewriting files
  -e=false: report all errors (not just the first 10 on different lines)
  -l=false: list files whose formatting differs from goimport's
  -w=false: write result to (source) file instead of stdout
make: *** [fmt] Error 2
#

**Comment by tiedotguy** [comment]
You may need to update your `goimports`, it looks like you're downrev, although there's no -version or similar flag to check.

The `setup` target in Makefile will `go get` a number of tools, including `golang.org/x/tools/cmd/goimports`

**Comment by fred-cm** [comment]
Thanks guy, it works with the version 0-15 of goimports    
But still errors in txt joined 
[gostatsd-make.txt](https://github.com/atlassian/gostatsd/files/5830741/gostatsd-make.txt)

**Comment by fred-cm** [comment]
Oh, `make setup ` to do first, bur after in readme :)
I try again

**Comment by tiedotguy** [comment]
Looks like a similar issue, except with `gofmt`, although I'm not sure why that would be - the `gofmt` for 1.15.5 shouldn't be trying to make these changes.

`make build` should actually apply formatting, and not trigger a failure if there **are** violations, so I'm unclear why it's showing a conflict instead of just fixing it.  That suggests maybe a non-standard gofmt.

Can you try doing a `which go gofmt` and make sure they're running out of the same `bin` directory?
```
tdg@emu:~$ which go gofmt
/usr/local/go/bin/go
/usr/local/go/bin/gofmt
```

If you're just looking to build, you could also edit the Makefile and comment out the contents of the `fmt` block (keep the block but # out the commands in it).

**Comment by fred-cm** [comment]
Not better
[gostatsd-make-1.txt](https://github.com/atlassian/gostatsd/files/5830875/gostatsd-make-1.txt)

`go `and `gofmt `belong to the same rpm and all is ok
I can't see what is wrong
```
# type go gofmt
go is /usr/bin/go
gofmt is /usr/bin/gofmt
# rpm -qf /usr/bin/go /usr/bin/gofmt
golang-bin-1.15.5-1.el7.x86_64
golang-bin-1.15.5-1.el7.x86_64
# rpm -qV golang-bin # <- we check rpm 
#

```

**Comment by tiedotguy** [comment]
Very strange.  I don't know a lot about installing go from a package, I've always just used the tgz.  It looks like golang.org doesn't offer rpms, is it an rpm provided by your distribution? If so, I wonder if they're doing something odd.

These lines are also interesting:
```
./pkg/backends/datadog/flush_test.go:19:69: missing ',' in composite literal
```

This is from the usage of `_` in literals:
```
		{"Positive value within float64 range should return unchanged", 12_345 /* <----- */, 12_345},
```

This syntax was added in 1.13, which suggests your gofmt is running a pre-1.13 dialect of go.

**Comment by fred-cm** [comment]
Almost ... :) 
```
go build -i -v -o build/bin/$(uname -s | tr A-Z a-z)/gostatsd -ldflags "-s -X main.Version=$(git describe --abbrev=0 --tags) -X main.GitCommit=$(git rev-parse --short HEAD) -X main.BuildDate=$(date +%Y-%m-%d-%H:%M)" github.com/atlassian/gostatsd/cmd/gostatsd
github.com/atlassian/gostatsd/pkg/statsd
# github.com/atlassian/gostatsd/pkg/statsd
pkg/statsd/statsd.go:81:11: undefined: reuseport
make: *** [build] Error 2
```

**Comment by fred-cm** [comment]
> This syntax was added in 1.13, which suggests your gofmt is running a pre-1.13 dialect of go.

Maybe, the rpm is here https://centos.pkgs.org/7/epel-x86_64/golang-1.15.5-1.el7.x86_64.rpm.html

**Comment by tiedotguy** [comment]
This time it's failing because...
```
	"github.com/libp2p/go-reuseport"
```

is not being detected as `reuseport`.  That I'm less sure on how to troubleshoot though, but I still suspect there's some weird version thing happening, possibly with a change in how golang handles modules.  Near as I can tell the binaries in the rpm (actually its dependency of golang-bin) are what's expected though.

My recommendation, if you can, is to use the docker build.  If you have docker, and run a `make docker`, it will build both the binary of `build/bin/linux/gostatsd`, and the docker image of `atlassianlabs/gostatsd-amd64:(git commit hash)`.

If you'd prefer to stay out of the docker ecosystem, I'd suggest installing golang from the tgz at https://golang.org/dl/, in to an isolated directory.

Apart from that, I'm not sure what other guidance I can give.

**Comment by fred-cm** [comment]
Thanks a lot guy
With docker :
```
docker run \
        --rm \
        -v "/root/go":"/gopath" \
        -w "/gopath/src/github.com/atlassian/gostatsd" \
        -e GOPATH="/gopath" \
        -e CGO_ENABLED=0 \
        golang:1.13.6   \
        go build -o build/bin/linux/gostatsd -ldflags "-s -X main.Version=$(git describe --abbrev=0 --tags) -X main.GitCommit=$(git rev-parse --short HEAD) -X main.BuildDate=$(date +%Y-%m-%d-%H:%M)" github.com/atlassian/gostatsd/cmd/gostatsd
container_linux.go:247: starting container process caused "chdir to cwd (\"/gopath/src/github.com/atlassian/gostatsd\") set in config.json failed: no such file or directory"
/usr/bin/docker-current: Error response from daemon: oci runtime error: container_linux.go:247: starting container process caused "chdir to cwd (\"/gopath/src/github.com/atlassian/gostatsd\") set in config.json failed: no such file or directory".
make: *** [docker] Error 127
```
However : 
```
# env |grep GO
GOPATH=/root/go
#
```
Should I create `/gopath/src ...` ?

**Comment by tiedotguy** [comment]
You need to have the source code cloned in to `$GOPATH/src/github.com/atlassian/gostatsd`, so something like `/root/go/src/github.com/atlassian/gostatsd`

**Comment by tiedotguy** [comment]
Then /root/go will be mounted in the docker container as /gopath, which exposes /root/go/src/github.com/atlassian/gostatsd as /gopath/src/github.com/atlassian/gostatsd

**Comment by fred-cm** [comment]
From the new working directory in my $GOPATH : 
```
# make docker
docker pull golang:1.13.6
Trying to pull repository docker.io/library/golang ...
1.13.6: Pulling from docker.io/library/golang
Digest: sha256:04bdcb522081df9c95e5888ada7da60da18fd0b0eae9423fdf05a477e0894352
Status: Image is up to date for docker.io/golang:1.13.6
docker run \
        --rm \
        -v "/root/go":"/gopath" \
        -w "/gopath/src/github.com/atlassian/gostatsd" \
        -e GOPATH="/gopath" \
        -e CGO_ENABLED=0 \
        golang:1.13.6   \
        go build -o build/bin/linux/gostatsd -ldflags "-s -X main.Version=$(git describe --abbrev=0 --tags) -X main.GitCommit=$(git rev-parse --short HEAD) -X main.BuildDate=$(date +%Y-%m-%d-%H:%M)" github.com/atlassian/gostatsd/cmd/gostatsd
# github.com/atlassian/gostatsd/pkg/statsd
pkg/statsd/statsd.go:81:11: undefined: reuseport
make: *** [docker] Error 2
#
```
I think this bug should be solved, maybe being more strict in names ?

**Comment by tiedotguy** [comment]
I think there's something either in your `/root/go/pkg/` or `/root/go/src` directory which is causing it confusion.  Can you try doing a fresh clone of the repo, and then from that directory, run:
```
docker run --rm \
  -v "$(pwd):/gopath/src/github.com/atlassian/gostatsd" \
  -w "/gopath/src/github.com/atlassian/gostatsd" \
  -e GOPATH=/gopath \
  golang:1.13.6 \
  go build -race -o build/bin/linux/gostatsd -ldflags "-X main.Version=29.0.0 -X main.GitCommit=c6f65b6 -X main.BuildDate=2021-01-19-03:17" github.com/atlassian/gostatsd/cmd/gostatsd
```

This should build the code with **nothing** external except the freshly cloned repo (which is mounted in to the container with the `-v`).

If this works, try renaming /root/go/pkg to something else temporarily (ie, /root/go/pkg_), and trying the `make docker` from the original directory again.

**Comment by fred-cm** [comment]
Thanks guy
```
# pwd
/root/go/src/github.com/atlassian/gostatsd
# git pull --all
Fetching origin
Already up to date.
# docker run --rm \
>   -v "$(pwd):/gopath/src/github.com/atlassian/gostatsd" \
>   -w "/gopath/src/github.com/atlassian/gostatsd" \
>   -e GOPATH=/gopath \
>   golang:1.13.6 \
>   go build -race -o build/bin/linux/gostatsd -ldflags "-X main.Version=29.0.0 -X main.GitCommit=c6f65b6 -X main.BuildDate=2021-01-19-03:17" github.com/atlassian/gostatsd/cmd/gostatsd
Unable to find image 'golang:1.13.6' locally
Trying to pull repository docker.io/library/golang ...
1.13.6: Pulling from docker.io/library/golang
8f0fdd3eaac0: Pull complete
d918eaefd9de: Pull complete
43bf3e3107f5: Pull complete
27622921edb2: Pull complete
f862a94ee651: Pull complete
410143ccff32: Pull complete
4e820fb4177f: Pull complete
Digest: sha256:04bdcb522081df9c95e5888ada7da60da18fd0b0eae9423fdf05a477e0894352
Status: Downloaded newer image for docker.io/golang:1.13.6
go: github.com/ash2k/stager@v0.0.0-20170622123058-6e9c7b0eacd4: Get https://proxy.golang.org/github.com/ash2k/stager/@v/v0.0.0-20170622123058-6e9c7b0eacd4.mod: dial tcp 172.217.168.241:443: i/o timeout
#
```
New try tomorrow

**Comment by tiedotguy** [comment]
That may have been a temporary timeout, does it repeat if you run it again?

**Comment by fred-cm** [comment]
Hello guy, same timeout this morning ....

**Comment by tiedotguy** [comment]
Odd, sounds like your docker can't reach the internet.  While the `pkg` directory is removed/renamed, can you try the `make build` from the original repo again?

**Comment by fred-cm** [comment]
Great guy, I passed proxy to docker, and
```
#  ./build/bin/linux/gostatsd --version
Version: 29.0.0 - Commit: c6f65b6 - Date: 2021-01-19-03:17
#
```
I must use opentsdb as backend, I've seen the backend interface, do you have an example of a backend implementation ? where to put the backend code, etc ?

**Comment by tiedotguy** [comment]
Awesome!

Backends live in `pkg/backends/<name>`, and need to be added to `pkg/backends/backends.go` so it's discoverable.

I would recommend using influxdb as a starting point as it's received the most attention recently, and the others are generally a bit less polished.  If you're using the telnet api in opentsdb, the `graphite` backend might be suitable to start as well, as it's more of a "streaming" model, and not HTTP based.

I'm happy to provide feedback/guidance on partial work as well, you can raise a PR and add me as a reviewer.

I'll leave this issue open in case you have other questions, but if you don't, feel free to close it off.

**Comment by fred-cm** [comment]
Thanks a lot guy, I'm going to take a look, yes I can close it, regards.
