### ISSUE TITLE
Howto / full config.toml example ? 

### ISSUE THREAD

**Issue by fred-cm** [atlassian/gostatsd#365]
Hello

The readme says : It is configured through the **top level server-mode** configuration setting.
https://github.com/atlassian/gostatsd#configuring-the-server-mode

And I would like to disable internal metrics, which directive is in the same section of readme, so my config is :
```
[server-mode]
standalone='true'
statser-type='null'
[graphite]
address = "localhost:2003"
dial_timeout = '3s'
write_timeout = '10s'
mode = 'tags'
```
But this doesn't work .. an example in the readme is welcome :)

**Comment by tiedotguy** [comment]
server-mode is a key in the top level, it has no `[name]` section, so it would look something like:

```
server-mode='standalone'
statser-type='null'
backends=['graphite']

[graphite]
address='localhost:2003'
...
```

There's an issue open to redo the documentation (#264), but I want to get clustering done before then, which is blocked on other approvers :(

**Comment by fred-cm** [comment]
Thanks guy!
