### ISSUE TITLE
Scaling out

### ISSUE THREAD

**Issue by hartfordfive** [atlassian/gostatsd#38]
In your documentation section **Load balancing and scaling out**, you mention it's possible to send requests to multiple gostatsd instances, which can then send the stats to another main gostatsd instance.  

I would like to do something similar although, instead of sending requests to a load-balanced pool of gostatsd instances, each server would report data to it's own local gostatsd process, which would then report those stats to a central gostatsd server.  Would you have any configuration examples I could follow to achieve this type of setup?

Thank you

**Comment by jtblin** [comment]
@hartfordfive I think this is completely possible and trivial to implement. Just send to `localhost:8125` to the local gostatsd server and have each loca gostatsd configured to run with `--backends= statsdaemon` and `config-path=/path/to/config.toml` pointing to a config file with something like:

```
[statsdaemon]

	address = "your-gostatsd-master-ip-or-domain:8125"
```

By default each local statsd is going to flush every second, you can change that to a larger value if you want but even if you have thousands of hosts, the master should be able to handle the load without issue (we've benchmarked it at hundreds of packets per second).

**Comment by aelse** [comment]
Appears to be supported by existing config. Closing this off.
