### ISSUE TITLE
Problems with statsdaemon backend writing to etsy statsd

### ISSUE THREAD

**Issue by natemueller** [atlassian/gostatsd#60]
I'm trying to set this service up to feed into an etsy statsd server with the statsdaemon backend.  The etsy server is rejecting the messages as invalid because it doesn't understand the tag syntax:

``
Sep  1 19:39:39 statsd-cyanite-1 statsd: 1 Sep 19:39:39 - DEBUG: Bad line: 0.002660,g,#aggregator_id in msg "statsd.processing_time:0.002660|g|#aggregator_id:1,s:luneta-3.ec2.nearbuysystems.com"
``

I can't figure out how to remove the tags from the backend and I'm also surprised that no one has run into this before.  Am I missing something stupid?  If not I'd be happy to contribute a fix.  Would you prefer a new backend or a config option for the statsdaemon one?

**Comment by ash2k** [comment]
I think it makes sense to add an option to disable tags for this backend. PRs welcome, but make sure to follow the process https://github.com/atlassian/gostatsd#contributors
