### ISSUE TITLE
Graphite backend ignores tags

### ISSUE THREAD

**Issue by glennslaven** [atlassian/gostatsd#78]
The functions inside `preparePayload` in `/backend/backends/graphite/graphite.go` accept the `tagsKey` parameter and each metric is prepared based on its tag. However the tag is never used in constructing the metric name to send to graphite.

So what happens is that if you have metric key `a.b.c` that is broken up into 10 tags, the metric `a.b.c` is sent to graphite 10 times with the same name & timestamp, but with the various values for each of the tags.  Then graphite simply takes the last one to arrive and put that in as the value for that timestamp, the other values are lost.

Ideally if there is a tag, the `preparePayload` function would insert it as (probably) a dot suffix after the key name.

**Comment by ash2k** [comment]
@glennslaven thanks for reporting this, we should probably add a configuration option to tweak this. However note that this is kind of related to the other issue you created (#77) - how timers are going to work? It is not clear.

**Comment by glennslaven** [comment]
@ash2k to be honest I'm not sure , I just assumed the timers were supposed to be fragmented by the tags :)

I suppose the other alternative is to keep the timers in one bucket and duplicate the data across the tags, although at that point the tags seem kind of useless.

**Comment by ivan-section-io** [comment]
Tags are part of the aggregation mechanism and should be output if provided.
The key to #77 (for graphite) is to not include a tag in the first place.
I think the only question is where tags belong:, prepended, appended, or even just before the derived stat name.
Including the tag (in some fashion) is the only safe option.
I'm sure a PR will be coming from @glennslaven shortly.

**Comment by tiedotguy** [comment]
@glennslaven, I've added 1.1 tagging style support.  I realize that your original request was more about node style naming rather than actual tags (because the issue was raised a year before tagging was added), but hopefully this is a suitable alternative.  Please raise another issue if you specifically want node style.
