### ISSUE TITLE
Figure out what is wrong with requests to Datadog

### ISSUE THREAD

**Issue by ash2k** [atlassian/gostatsd#96]
> {"level":"info","msg":"[datadog] failed request status: 400\n\u003chtml\u003e\u003cbody\u003e\u003ch1\u003e400 Bad request\u003c/h1\u003e\nYour browser sent an invalid request.\n\u003c/body\u003e\u003c/html\u003e\n","time":"2017-01-26T20:25:08Z"}

**Comment by aelse** [comment]
We're using gostatsd heavily with DD and afaik we haven't seen this recently. If the problem resurfaces we can look at it.
